package jave.api.odedApi.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NonNull;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@AllArgsConstructor
@Document("Task")              // Maps Entity class objects to JSON formatted Documents

public class Task {
    @Id                 // making this variable as ID, will be auto-generated by MongoDB
    private String id;

    @NonNull
    private Integer taskId;
    @NonNull
    private String taskCategory;
    @NonNull
    private String taskAction;
    @NonNull
    private String taskDescription;
    @NonNull
    private Integer taskStars;

    public Task(){}

    public Task(@NonNull Integer taskId, @NonNull String taskCategory, @NonNull String taskAction, @NonNull String taskDescription, @NonNull Integer taskStars)
    {
        this.taskId = taskId;
        this.taskCategory = taskCategory;
        this.taskAction = taskAction;
        this.taskDescription = taskDescription;
        this.taskStars = taskStars;
    }

    @Override
    public String toString()
    {
        return String.format("Task[taskId=%d, taskCaregory='%s', taskAction='%s', taskDescription='%s', taskStars=%d",taskId,taskCategory,taskAction,taskDescription,taskStars);
    }
}

