package jave.api.odedApi.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@Data
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor
@Document              // Maps Entity class objects to JSON formatted Documents

public class Task {
    @Id                 // making this variable as ID, will be auto-generated by MongoDB
    private String id;

    @NonNull
    private Integer taskId;
    @NonNull
    private String taskName;
    @NonNull
    private String taskDescription;
    @NonNull
    private Integer taskStars;

    public Task(){}

    public Task(@NonNull Integer taskId, @NonNull String taskName, @NonNull String taskDescription, @NonNull Integer taskStars)
    {
        this.taskId = taskId;
        this.taskName = taskName;
        this.taskDescription = taskDescription;
        this.taskStars = taskStars;
    }

    @Override
    public String toString()
    {
        return String.format("Task[taskId=%d, taskName='%s', taskDescription='%s', taskStars=%d",taskId,taskName,taskDescription,taskStars);
    }
}

